apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels: 
    {{ .Values.giropopsSenhas.labels | toYaml | nindent 4 }} 
spec:
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: {{ .Values.giropopsSenhas.service.port }}
      targetPort: {{ .Values.giropopsSenhas.service.targetPort }}
      name: http
  type: {{ .Values.giropopsSenhas.service.type }}
